export const dairy = [
    {
        id: "dairy-1",
        title: "Milk",
        // image: require('@/assets/dairy/milk.png'),
        price: 1.0,
        rating: 4.5,
        count: 20,
    },
    {
        id: "dairy-2",
        title: "Cheese",
        // image: require('@/assets/dairy/cheese.png'),
        price: 2.5,
        rating: 4.7,
        count: 15,
    },
    {
        id: "dairy-3",
        title: "Yogurt",
        // image: require('@/assets/dairy/yogurt.png'),
        price: 1.8,
        rating: 4.6,
        count: 12,
    },
    {
        id: "dairy-4",
        title: "Butter",
        // image: require('@/assets/dairy/butter.png'),
        price: 2.0,
        rating: 4.4,
        count: 10,
    },
    {
        id: "dairy-5",
        title: "Cream",
        // image: require('@/assets/dairy/cream.png'),
        price: 2.2,
        rating: 4.5,
        count: 8,
    },
    {
        id: "dairy-6",
        title: "Sour Cream",
        // image: require('@/assets/dairy/sour_cream.png'),
        price: 2.4,
        rating: 4.6,
        count: 7,
    }
]