export const fruits = [
    {
        title: "Banana",
        image: require('@/assets/images/fruits/fruit1.png'),
        price: 1.99,
        rating: 4.5,
        count: 100,
    },
    {
        title: "Pepper",
        image: require('@/assets/images/fruits/fruit2.png'),
        price: 2.99,
        rating: 4.8,
        count: 217,
    },
    {
        title: "Orange",
        image: require('@/assets/images/fruits/fruit3.png'),
        price: 1.49,
        rating: 4.2,
        count: 150,
    },
    {
        title: "Lemon",
        image: require('@/assets/images/fruits/fruit4.png'),
        price: 3.99,
        rating: 4.7,
        count: 80,
    },
    {
        title: "Water Melon",
        image: require('@/assets/images/fruits/fruit5.png'),
        price: 2.49,
        rating: 4.8,
        count: 217,
    },
    {
        title: "Grape",
        image: require('@/assets/images/fruits/fruit6.png'),
        price: 1.69,
        rating: 4.8,
        count: 217,
    },
    {
        title: "Paw Paw",
        image: require('@/assets/images/fruits/fruit7.png'),
        price: 2.99,
        rating: 4.9,
        count: 107,
    },
    {
        title: "Strawberry",
        image: require('@/assets/images/fruits/fruit8.png'),
        price: 3.49,
        rating: 4.8,
        count: 150,
    },
    {
        title: "Apple",
        image: require('@/assets/images/fruits/fruit9.png'),
        price: 1.99,
        rating: 4.5,
        count: 200,
    },
    {
        title: "Mango",
        image: require('@/assets/images/fruits/fruit10.png'),
        price: 1.99,
        rating: 4.5,
        count: 200,
    }
];